name: Hello!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello Me!"
  date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say date
        run: |
          date
  list_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say list
        run: |
          ls